<?php

define('CDI_DATA_TYPE_ENTITY', 'entity');

function cdi_entities_cdi_data_types() {
  return array(
    CDI_DATA_TYPE_ENTITY => new CDIDataType(CDI_DATA_TYPE_ENTITY),
  );
}

function cdi_entities_cdi_receivers() {
  return array(
    CDI_DATA_TYPE_ENTITY => array(
      'receiver' => new CDIEntityReceiver(),
    ),
  );
}

function cdi_entities_cdi_enabled_modules() {
  return array(
    CDI_MODULE_LOAD,
    CDI_MODULE_ID,
    CDI_MODULE_SAVE,
  );
}